import os

import pandas as pd

from app.db import (
    get_batch_by_id,
    load_historical_profiles,
    save_clusters,
    save_predictions,
    save_profiles,
    update_batch_status,
)

from app.clustering import build_profile_clusters
from app.decisions.recommendations import add_recommendations
from app.features import build_features_for_candidate_pairs
from app.models.predict import predict_duplicate_scores
from app.spark_blocking import build_candidate_pairs_with_spark
from app.storage import read_batch_from_minio


def run_batch(batch_id: str) -> None:
    """Запускает обработку batch-файла по batch_id.

    Args:
        batch_id: UUID batch-записи из PostgreSQL.
    """
    print("Starting batch processing")
    print("Batch ID:", batch_id)

    batch = get_batch_by_id(batch_id)
    print("Batch found in PostgreSQL")
    print("Current status:", batch["status"])
    print("Object key:", batch["object_key"])

    update_batch_status(batch_id, "processing")
    print("Batch status updated to processing")

    try:
        batch_df = read_batch_from_minio(batch["object_key"])

        print("Batch loaded from MinIO successfully")
        print("Shape:", batch_df.shape)
        print("Columns:", list(batch_df.columns))
        print("Preview:")
        print(batch_df.head())

        saved_profiles_count = save_profiles(
            batch_id=batch_id,
            batch_df=batch_df,
            source_filename=batch["filename"],
        )

        print(f"Profiles saved to master table: {saved_profiles_count}")

        historical_profiles_df = load_historical_profiles(
            exclude_batch_id=batch_id,
        )

        print("Historical profiles loaded:", len(historical_profiles_df))

        new_profile_ids = set(batch_df["profile_id"].astype(str).unique())
        historical_profile_ids = set(historical_profiles_df["profile_id"].astype(str).unique())

        if historical_profiles_df.empty:
            all_profiles_df = batch_df.copy()
        else:
            all_profiles_df = pd.concat(
                [
                    batch_df,
                    historical_profiles_df,
                ],
                ignore_index=True,
                sort=False,
            )

        print("All profiles for blocking:", len(all_profiles_df))
        print("New unique profiles:", len(new_profile_ids))
        print("Historical unique profiles:", len(historical_profile_ids))

        candidate_pairs_df = build_candidate_pairs_with_spark(all_profiles_df)
        print("Candidate pairs generated by Spark before filtering:", len(candidate_pairs_df))

        candidate_pairs_df = filter_incremental_candidate_pairs(
            candidate_pairs_df=candidate_pairs_df,
            new_profile_ids=new_profile_ids,
            historical_profile_ids=historical_profile_ids,
        )

        print("Candidate pairs after incremental filtering:", len(candidate_pairs_df))

        features_df = build_features_for_candidate_pairs(
            batch_df=all_profiles_df,
            candidate_pairs=candidate_pairs_df,
        )
        print("Features generated:", len(features_df))

        if features_df.empty:
            print("No candidate pairs found")
            update_batch_status(batch_id, "completed")
            print("Batch status updated to completed")
            return

        predictions_df = predict_duplicate_scores(features_df)
        predictions_df = add_recommendations(predictions_df)

        predictions = [
            {
                "profile1": str(row["profile1"]),
                "profile2": str(row["profile2"]),
                "match_score": float(row["match_score"]),
                "is_duplicate": bool(row["is_duplicate"]),
                "recommendation": str(row["recommendation"]),
            }
            for _, row in predictions_df.iterrows()
        ]

        saved_count = save_predictions(batch_id, predictions)
        print(f"Predictions saved to PostgreSQL: {saved_count}")

        clusters = build_profile_clusters(
        predictions_df=predictions_df,
        batch_id=batch_id,
        recommendation_mode="auto_merge",
        )

        saved_clusters_count = save_clusters(
            batch_id=batch_id,
            clusters=clusters,
            recommendation_mode="auto_merge",
        )

        print(f"Cluster records saved to PostgreSQL: {saved_clusters_count}")

        print("Predictions preview:")
        print(
            predictions_df[
                [
                    "profile1",
                    "profile2",
                    "match_score",
                    "is_duplicate",
                    "recommendation",
                ]
            ]
        )

        update_batch_status(batch_id, "completed")
        print("Batch status updated to completed")

    except Exception:
        update_batch_status(batch_id, "failed")
        print("Batch status updated to failed")
        raise

def filter_incremental_candidate_pairs(
    candidate_pairs_df: pd.DataFrame,
    new_profile_ids: set[str],
    historical_profile_ids: set[str],
) -> pd.DataFrame:
    """Оставляет только пары new-new и new-historical.

    historical-historical пары не нужны, потому что старые профили
    уже были обработаны раньше.
    """
    if candidate_pairs_df.empty:
        return candidate_pairs_df

    result = candidate_pairs_df.copy()

    result["profile1"] = result["profile1"].astype(str)
    result["profile2"] = result["profile2"].astype(str)

    profile1_is_new = result["profile1"].isin(new_profile_ids)
    profile2_is_new = result["profile2"].isin(new_profile_ids)

    profile1_is_historical = result["profile1"].isin(historical_profile_ids)
    profile2_is_historical = result["profile2"].isin(historical_profile_ids)

    new_new_mask = profile1_is_new & profile2_is_new

    new_historical_mask = (
        (profile1_is_new & profile2_is_historical)
        | (profile1_is_historical & profile2_is_new)
    )

    return result[new_new_mask | new_historical_mask].reset_index(drop=True)

def main() -> None:
    """CLI entrypoint для запуска batch-processing из Docker."""
    batch_id = os.getenv("BATCH_ID")

    if not batch_id:
        raise ValueError(
            "BATCH_ID is required. "
            "Pass it with: docker compose run --rm -e BATCH_ID=<uuid> pipeline-worker"
        )

    run_batch(batch_id)


if __name__ == "__main__":
    main()